### ISSUE TITLE
 Entry, ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by arashbi** [start-react/native-starter-kit#46]
Checkedout from repo, ran npm install and link.
Error message while running application:
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/NativeStarterKit.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by web-jenezis** [comment]
Got the same error when tried to built project:

```
** BUILD FAILED **


The following build commands failed:
    CompileC /Users/jenezis/sites/native-starter-kit/ios/build/Build/Intermediates/RCTWebSocket.build/Debug-iphonesimulator/RCTWebSocket.build/Objects-normal/x86_64/RCTSRWebSocket.o RCTSRWebSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/NativeStarterKit.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/NativeStarterKit.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

**Comment by SupriyaKalghatgi** [comment]
@arashbi @web-jenezis Can I know which version of Xcode you are working with?

**Comment by randytorres** [comment]
Same issue for me and I'm using Xcode 8.1

```** BUILD FAILED **


The following build commands failed:
        CompileC /Users/randytorres/Downloads/native-starter-kit-master/ios/build/Build/Intermediates/RCTWebSocket.build/Debug-iphonesimulator/RCTWebSocket.build/Objects-normal/x86_64/RCTSRWebSocket.o RCTSRWebSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/NativeStarterKit.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/NativeStarterKit.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist```

**Comment by randytorres** [comment]
Same issue for me and I'm using Xcode 8.1

```
** BUILD FAILED **

The following build commands failed:
CompileC /Users/randytorres/Downloads/native-starter-kit-master/ios/build/Build/Intermediates/RCTWebSocket.build/Debug-iphonesimulator/RCTWebSocket.build/Objects-normal/x86_64/RCTSRWebSocket.o RCTSRWebSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/NativeStarterKit.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/NativeStarterKit.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

**Comment by pranavrajs** [comment]
Same issue here with Xcode 8.1

**Comment by pranavrajs** [comment]
Upgraded RN version to 0.36.0. Did `react-native upgrade` and `react-native link`. Now issue is solved.

**Comment by SupriyaKalghatgi** [comment]
@randytorres Did you try deleting Custom Compiler Flags in Xcode?

**Comment by randytorres** [comment]
@SupriyaKalghatgi No not sure how to do that. I tried what @pranavrajs recommended but its still not working

**Comment by SupriyaKalghatgi** [comment]
@randytorres Check [here](https://github.com/facebook/react-native/issues/8584#issuecomment-236366222)

**Comment by SupriyaKalghatgi** [comment]
@randytorres Did you got it running?

Also NSK 5.2.1 has been released.
